d /var/lib/oci-acme-publisher 0700 oci-acme-publisher oci-acme-publisher -
d /var/lib/oci-acme-publisher/acme 0700 oci-acme-publisher oci-acme-publisher -
d /var/lib/oci-acme-publisher/certificates 0700 oci-acme-publisher oci-acme-publisher -
d /var/log/oci-acme-publisher 0750 oci-acme-publisher oci-acme-publisher -
d /var/lib/oci-acme-http01 0750 oci-acme-publisher oci-acme-challenge -
d /var/lib/oci-acme-http01/webroots 2750 oci-acme-publisher oci-acme-challenge -
d /run/oci-acme-publisher 0750 oci-acme-publisher oci-acme-publisher -
