"""Safe local operator workflows used by the public ``oci-acme`` command."""

from __future__ import annotations

import json
import os
import re
from grp import getgrnam
from pathlib import Path
from pwd import getpwnam
from typing import Any

import yaml

from .config import load_config, normalize_domain
from .errors import ConfigurationError

DEFAULT_CONFIG_DIRECTORY = "/etc/oci-acme-publisher"
_CERTIFICATE_ID = re.compile(r"^[a-z][a-z0-9-]{0,62}$")

_SETTINGS_TEMPLATE = """# Generated by `oci-acme config init`.
# Fill every EXAMPLE value before use.
schema_version: 4\n\
global:\n\
  environment: staging\n\
  state_dir: /var/lib/oci-acme-publisher\n\
  log_level: INFO\n\
  json_logging: true\n\
compatibility:\n\
  # Set this only after retaining successful live compatibility evidence.\n\
  live_verified: false\n\
  enforce_documented_subject_country: true\n\
  require_complete_chain_to_root: true\n\
  reject_mixed_algorithm_chain: true\n\
acme:\n\
  email: admin@example.com\n\
  agree_to_terms: true\n\
  directory_url: https://acme-staging-v02.api.letsencrypt.org/directory\n\
  account_key_path: /var/lib/oci-acme-publisher/acme/account.key\n\
  certificates_dir: /var/lib/oci-acme-publisher/certificates\n\
  operation_timeout_seconds: 1800\n\
  renew_before_days: 30\n\
  rotate_private_key_on_renewal: true\n\
http01:\n\
  webroot_base: /var/lib/oci-acme-http01/webroots\n\
  responder:\n\
    bind_address: 127.0.0.1\n\
    bind_port: 8080\n\
  self_check: {}\n\
oci:\n\
  authentication: instance_principal\n\
monitoring:\n\
  warning_days: 20\n\
  critical_days: 7\n"""

_CERTIFICATE_TEMPLATE = """# One file per certificate. Rename this file before production use.\n\
certificate:\n\
  id: example-com\n\
  webroot_id: example-com\n\
  common_name: example.com\n\
  domains: [example.com]\n\
  key:\n\
    type: rsa\n\
    rsa_size: 2048\n\
  chain:\n\
    root_pem_path: /etc/oci-acme-publisher/roots/isrg-root-x1.pem\n\
    allowed_root_sha256: [\"0000000000000000000000000000000000000000000000000000000000000000\"]\n\
    allowed_issuer_common_names: [\"EXAMPLE ISSUER\"]\n\
  oci:\n\
    region: eu-frankfurt-1\n\
    compartment_ocid: ocid1.compartment.oc1..EXAMPLE\n\
    certificate_ocid: null\n\
    certificate_name: example-com\n\
  audit:\n\
    mode: observe\n\
    automatic_rollback_on_failure: false\n\
    endpoints:\n\
      - hostname: example.com\n\
        port: 443\n"""


def initialize_configuration(config_directory: str, *, dry_run: bool = False) -> tuple[str, ...]:
    """Create an intentionally incomplete staging configuration without overwriting data."""
    directory = Path(config_directory)
    if not directory.is_absolute():
        raise ConfigurationError("configuration directory must be an absolute path")
    if directory.exists() and not directory.is_dir():
        raise ConfigurationError("configuration path exists and is not a directory")
    if directory.exists() and any(directory.iterdir()):
        raise ConfigurationError("configuration directory is not empty; refusing to overwrite it")

    files = (
        directory / "settings.yaml",
        directory / "certificates" / "example-com.yaml",
    )
    if dry_run:
        return tuple(str(path) for path in files)

    directory.mkdir(mode=0o750, parents=True, exist_ok=True)
    certificates = directory / "certificates"
    roots = directory / "roots"
    certificates.mkdir(mode=0o750)
    roots.mkdir(mode=0o750)
    _write_new(files[0], _SETTINGS_TEMPLATE)
    _write_new(files[1], _CERTIFICATE_TEMPLATE)
    _apply_runtime_ownership(directory, files)
    return tuple(str(path) for path in files)


def _write_new(path: Path, contents: str) -> None:
    """Write a new configuration file with restrictive permissions only."""
    descriptor = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640)
    with os.fdopen(descriptor, "w", encoding="utf-8") as output:
        output.write(contents)


def _apply_runtime_ownership(directory: Path, files: tuple[Path, ...]) -> None:
    """Apply installed service-account permissions only when the operator is root."""
    if os.geteuid() != 0:
        return
    try:
        publisher = getpwnam("oci-acme-publisher")
        challenge = getgrnam("oci-acme-challenge")
    except KeyError as error:
        raise ConfigurationError(
            "OCI ACME service accounts are unavailable; "
            "install the package before initializing config"
        ) from error
    os.chown(directory, 0, publisher.pw_gid)
    os.chmod(directory, 0o751)  # noqa: S103 - restricted root-owned config directory
    certificates = directory / "certificates"
    roots = directory / "roots"
    os.chown(certificates, publisher.pw_uid, challenge.gr_gid)
    os.chmod(certificates, 0o750)  # noqa: S103 - service-owned certificate directory
    os.chown(roots, 0, publisher.pw_gid)
    os.chmod(roots, 0o750)  # noqa: S103 - root-owned trusted-root directory
    for path in files:
        os.chown(path, publisher.pw_uid, challenge.gr_gid)
        os.chmod(path, 0o640)


def add_certificate(
    config_directory: str,
    *,
    certificate_id: str,
    domains: tuple[str, ...],
    region: str,
    compartment_ocid: str,
    certificate_ocid: str | None,
    dry_run: bool = False,
) -> str:
    """Add one independently managed certificate file without modifying settings."""
    directory = Path(config_directory)
    if not directory.is_absolute():
        raise ConfigurationError("configuration directory must be an absolute path")
    if _CERTIFICATE_ID.fullmatch(certificate_id) is None:
        raise ConfigurationError(
            "certificate id must contain lowercase letters, digits, and hyphens"
        )
    if not domains:
        raise ConfigurationError("at least one domain is required")
    try:
        normalized_domains = tuple(normalize_domain(domain) for domain in domains)
    except ValueError as error:
        raise ConfigurationError("one or more domains are invalid") from error
    if len(set(normalized_domains)) != len(normalized_domains):
        raise ConfigurationError("domains must be unique")
    if not region or any(character.isspace() for character in region):
        raise ConfigurationError("region must be a non-empty OCI region identifier")
    if not compartment_ocid.startswith("ocid1.compartment."):
        raise ConfigurationError("compartment OCID is invalid")
    if certificate_ocid is not None and not certificate_ocid.startswith("ocid1.certificate."):
        raise ConfigurationError("certificate OCID is invalid")

    path = directory / "certificates" / f"{certificate_id}.yaml"
    if path.exists():
        raise ConfigurationError(
            "certificate configuration already exists; refusing to overwrite it"
        )
    document = {
        "certificate": {
            "id": certificate_id,
            "webroot_id": certificate_id,
            "common_name": normalized_domains[0],
            "domains": list(normalized_domains),
            "key": {"type": "rsa", "rsa_size": 2048},
            "chain": {
                "root_pem_path": "/etc/oci-acme-publisher/roots/isrg-root-x1.pem",
                "allowed_root_sha256": ["0" * 64],
                "allowed_issuer_common_names": ["EXAMPLE ISSUER"],
            },
            "oci": {
                "region": region,
                "compartment_ocid": compartment_ocid,
                "certificate_ocid": certificate_ocid,
                "certificate_name": certificate_id,
            },
            "audit": {
                "mode": "observe",
                "automatic_rollback_on_failure": False,
                "endpoints": [{"hostname": normalized_domains[0], "port": 443}],
            },
        }
    }
    if not dry_run:
        if not path.parent.is_dir():
            raise ConfigurationError("configuration directory has not been initialized")
        _write_new(path, yaml.safe_dump(document, sort_keys=False))
        _apply_runtime_ownership(directory, (path,))
    return str(path)


def effective_configuration(path: str) -> dict[str, Any]:
    """Render normalized configuration without exposing personal contact details."""
    document = load_config(path).model_dump(mode="json", by_alias=True)
    acme = document.get("acme")
    if isinstance(acme, dict):
        acme["email"] = "[REDACTED]"
    notifications = document.get("notifications")
    if isinstance(notifications, dict) and notifications.get("credential_ref") is not None:
        notifications["credential_ref"] = "[REDACTED]"
    return document


def diagnose_configuration(path: str) -> dict[str, object]:
    """Return bounded, local, redacted diagnostics without network operations."""
    config = load_config(path)
    return {
        "result": "DIAGNOSE_CONFIGURATION_VALID",
        "config_path": str(Path(path)),
        "environment": config.global_.environment.value,
        "certificate_ids": [certificate.id for certificate in config.certificates],
        "responder": {
            "bind_address": config.http01.responder.bind_address,
            "bind_port": config.http01.responder.bind_port,
            "health_path": config.http01.responder.health_path,
            "readiness_path": config.http01.responder.readiness_path,
        },
        "next_action": "Run `oci-acme check --config <directory>` before issuance.",
    }


def render_json(value: object) -> str:
    """Render deterministic command output for people and automation."""
    return json.dumps(value, sort_keys=True)
